export const GET_MENUS = 'GET_MENUS';
export const GET_MENUS_SUCCESS = 'GET_MENUS_SUCCESS';
export const GET_MENUS_ERROR = 'GET_MENUS_ERROR';

export const ADD_MENU = 'ADD_MENU';
export const ADD_MENU_SUCCESS = 'ADD_MENU_SUCCESS';
export const ADD_MENU_ERROR = 'ADD_MENU_ERROR';

export const DELETE_MENU = 'DELETE_MENU';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';
export const DELETE_MENU_ERROR = 'DELETE_MENU_ERROR';