export const GET_MENUS = 'GET_MENUS';
export const GET_MENUS_SUCCESS = 'GET_MENUS_SUCCESS';
export const GET_MENUS_ERROR = 'GET_MENUS_ERROR';

// Standalone updates. Local state keeps track of the rest
export const EDIT_MENU_ITEM_SUCCESS = 'EDIT_MENU_ITEM_SUCCESS';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const EDIT_MAIN_HEADER_SUCCESS = 'EDIT_MAIN_HEADER_SUCCESS';
export const UPDATE_CONTEXT = 'UPDATE_CONTEXT';
export const UPDATE_CURRENT_MENU = 'UPDATE_CURRENT_MENU';

export const ADD_MENU = 'ADD_MENU';
export const ADD_MENU_SUCCESS = 'ADD_MENU_SUCCESS';
export const ADD_MENU_ERROR = 'ADD_MENU_ERROR';

export const DELETE_MENU = 'DELETE_MENU';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';
export const DELETE_MENU_ERROR = 'DELETE_MENU_ERROR';