export const GET_PERMISSIONS = "GET_PERMISSIONS"
export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS"
export const GET_PERMISSIONS_ERROR = "GET_PERMISSIONS_ERROR"
export const SET_PERMISSION_EMAIL = "SET_PERMISSION_EMAIL"
