
export const GET_HOME_CONFIG = "GET_HOME_CONFIG";
export const GET_HOME_CONFIG_SUCCESS = "GET_HOME_CONFIG_SUCCESS";
export const GET_HOME_CONFIG_ERROR = "GET_HOME_CONFIG_ERROR";

export const EDIT_RESTAURANT_NAME = "EDIT_RESTAURANT_NAME";
export const EDIT_RESTAURANT_DESCRIPTION = "EDIT_RESTAURANT_DESCRIPTION"