
export const GET_HOME_CONFIG = "GET_HOME_CONFIG";
export const GET_HOME_CONFIG_SUCCESS = "GET_HOME_CONFIG_SUCCESS";
export const GET_HOME_CONFIG_ERROR = "GET_HOME_CONFIG_ERROR";

export const EDIT_RESTAURANT_NAME = "EDIT_RESTAURANT_NAME";
export const EDIT_RESTAURANT_DESCRIPTION = "EDIT_RESTAURANT_DESCRIPTION"
export const ADD_RESTAURANT_LINK = "ADD_RESTAURANT_LINK"
export const REMOVE_RESTAURANT_LINK = "REMOVE_RESTAURANT_LINK"
export const UPDATE_HOME_PHOTO = "UPDATE_HOME_PHOTO"
export const ADD_GOTO_LINK = "ADD_GOTO_LINK"
export const EDIT_GOTO_LINK = "EDIT_GOTO_LINK"