
export const GET_HOME_CONFIG = "GET_HOME_CONFIG";
export const GET_HOME_CONFIG_SUCCESS = "GET_HOME_CONFIG_SUCCESS";
export const GET_HOME_CONFIG_ERROR = "GET_HOME_CONFIG_ERROR";
export const ADD_RESTAURANT_NAME = "ADD_RESTAURANT_NAME";