export const GET_INVENTORY_ITEMS = 'GET_INVENTORY_ITEMS';
export const GET_INVENTORY_ITEMS_SUCCESS = 'GET_INVENTORY_ITEMS_SUCCESS';
export const GET_INVENTORY_ITEMS_ERROR = 'GET_INVENTORY_ITEMS_ERROR';