export const GET_INVENTORY_ITEMS = 'GET_INVENTORY_ITEMS';
export const GET_INVENTORY_ITEMS_SUCCESS = 'GET_INVENTORY_ITEMS_SUCCESS';
export const GET_INVENTORY_ITEMS_ERROR = 'GET_INVENTORY_ITEMS_ERROR';

export const ADD_INVENTORY_ITEM = 'ADD_INVENTORY_ITEM';
export const REMOVE_INVENTORY_ITEM = 'REMOVE_INVENTORY_ITEM';
export const EDIT_INVENTORY_ITEM = 'EDIT_INVENTORY_ITEM';